name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Obtener código del repositorio
        uses: actions/checkout@v3

      - name: Configurar conexión SSH y desplegar
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@IP_PUBLICA << 'EOF'
            sudo rm -rf /var/www/html/*
            sudo cp -r * /var/www/html/
            sudo systemctl restart nginx
            exit
          EOF
