name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código del repositorio
        uses: actions/checkout@v3

      - name: Configurar conexión SSH y desplegar
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Copiar los archivos del repositorio al servidor EC2
          scp -o StrictHostKeyChecking=no -i private_key.pem -r * ubuntu@18.217.118.156:/home/ubuntu/app/

          # Ejecutar comandos dentro de la instancia EC2
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@18.217.118.156 << 'EOF'
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/app/* /var/www/html/
            sudo systemctl restart nginx
            exit
          EOF
